README.md
It's clear that the `task:` entry in the pipeline must run with `privileged: true`. But it's easy to forget to add that flag on the `fly` command line. (Or, in my case, confuse it with the pipeline flag.)
=> Called out running task with elevated privileges

README.md, cmd/build/main.go, task.go, task_test.go, testdata/labels/Dockerfile, testdata/labels/label_file, testdata/labels/label_layer.dockerfile, testdata/labels/labels_file, types.go
Adds support for adding labels to images at build time via `LABEL_*` or `LABELS_FILE` params.
Fixes: https://github.com/vito/oci-build-task/issues/41
=> Labels support

README.md, cmd/build/main.go, task.go, task_test.go, testdata/buildkit-secret/Dockerfile, testdata/buildkit-secret/secret, types.go
Buildkit supports the ability to mount secrets into certain steps of a dockerfile, via `--mount=type=secret,id=[secret-id]`. I've attempted to add support for setting up these secrets via the `BUILDKIT_SECRET_[secret-id]` environment variables.
I've been able to test this in Concourse and build an image which uses credentials passed in via a secret 🙂
=> Add support for BuildKit secrets

task.go
With the default min setting only the cache of the final image is exported resulting in poor cache performance for most multi-stage dockerfiles as the heavy work is usually happening in intermediate images.
This will lead to a bigger cache size but improves build time as more parts of multi-stage builds are cached.
Fixes #26
Signed-off-by: Fabian Ruff <fabian.ruff@sap.com>
=> change cache export mode from min to max

README.md
When debugging someone else's pipeline I read past the text above this several times and kept wondering why we ended up with a "file not found" error.
=> Be more explicit about UNPACK_ROOTFS in example expecting it

Dockerfile, scripts/setup-buildkit.sh
Always worth keeping up-to-date right?
=> Buildkit 0.8.3 / Rootlesskit 0.14.2

README.md, task.go, task_test.go, types.go
Allows users to build images for other platforms like `linux/arm64`
=> Add IMAGE_PLATFORM param

registry.go, task_test.go, testdata/image-args/Dockerfile.uppercase
If a Dockerfile contained a build arg that was uppercase for referencing
an image, building would result in an error:
```
failed to parse stage name "localhost:42545/FIRST_IMAGE": invalid reference format: repository name must be lowercase
```
This commit allows users to specify args as all uppercase and lowercases
the name behind the scenes. Uppercase args are common in wild
Dockerfiles
=> Fix image args that are uppercase

unpack.go
Sometimes builds would be stuck on 100% and never complete.
Similar to:
https://github.com/concourse/registry-image-resource/issues/303
Completing progress bars explicitly solves this issue for me.
Signed-off-by: Nico Schieder <code@nico-schieder.de>
=> Fix infinite wait on stuck progress bars

README.md
Hello,
In this PR, I've added the missing documentation for `$ADDITIONAL_TARGETS` and `$BUILDKIT_ADD_HOSTS` configuration env vars.
Best,
Benjamin
=> Document ADDITIONAL_TARGETS and BUILDKIT_ADD_HOSTS

Dockerfile
Hi,
I've noticed that some newer version of BuildKit is available, providing some fixes.
So, I suggest here we bump this task to benefit from those.
Best,
Benjamin
=> Bump buildkit to v0.9.3

cmd/task/main.go
Hello,
Here is an example of failure logs I have without this fix:
```
FATA[0010] failed to build: create local image registry: image from path: open alpine-latest/image.tar: no such file or directory 
FATA[0011] failed to run task: exit status 1            
```
And the Concourse task hangs until manually terminated.
So, I'm suggesting here a fix a a lack of cleanup on the BuildKit daemon whenever the `buildkit` CLI invocation fails.
Best,
Benjamin
=> Properly cleanup daemon on buildkit failure

README.md
Hi there!
While I'm using the _OCI build_ task for the first time, I've hit some quirks with the documentation.
Documentation prepends '$' to all task params, but this is irrelevant in the `params:` YAML dictionary of a task definition in a job's plan.
Here in this PR, I'm suggestion some fix in order to stick to this convention, and some wording for precising how the leading `$` signs are supposed to be understood.
One other option would be to remove the (possibly confusing)  prepended `$` altogether from the `params:` list! In which case, I'll be happy to submit another PR for that.
What do you think?
Benjamin
=> Un-confuse documentation about the $PARAM syntax used for tasks params

README.md, cmd/build/main.go, task.go, task_test.go
To preserve the existing meaning of `BUILDKIT_SECRET_`, a new `BUILDKIT_SECRETTEXT_` prefix is added, which writes content to a file before adding corresponding entry to the `BuildkitSecrets` map.
These contents are created in `buildkit-secrets/` inside the default temporary directory; since the Docker container this all happens in is transient, no need to clean them up.
See #78 for motivation.
=> Add support for passing secrets as text (#78)

Dockerfile
Motivating change is moby/buildkit#2926, whereby errors were not correctly propagated.
=> Bump buildkit to 0.10.4

Dockerfile
=> bump buidkit to 0.11.0 to support multi-arch build.

README.md
This change is to help prevent users from attempting `FROM base_image` when correct usage is `ARG base_image` followed by `FROM ${base_image}`.
=> README: Demonstrate how to use IMAGE_ARG

README.md
Previously the masked link had a whitespace between text and link so it didn't actually work and showed as 
```md
[multiple platforms] (https://docs.docker.com/desktop/extensions-sdk/extensions/multi-arch/)
```
=> docs(readme): fix masked link typo

README.md, go.mod, task.go, task_test.go, testdata/build-args/build_args_file.yaml
Adds key/value yaml files as possible input for build arg file. This allows for multiline args support in from build arg files.
Since build arg file splits on newlines, it's currently not possible to do so with build arg file option: Passing yaml would allow us to set the value of build args to any string, including newlines, making this possible:
`my-input/myvars.yaml`
```
foo: |
first line
second line
third line
```
```
- task my-oci-build-task
params:
BUILD_ARGS_FILE: my-input/myvars.yaml
platform: linux
image_resource:
type: registry-image
source:
repository: concourse/oci-build-task
inputs:
- name: my-input
```
setting the build arg of `foo` to:
```
first line
second line
third line
```
closes #122
=> Add support for build arg files in yaml format.

README.md, buildkitd.go, types.go
Params like `REGISTRY_MIRRORS` don't really scale well to cover a complex schema like buildkit's toml configuration. Plus, they can become out-of-date.
A param whose content is written verbatim to the config file allows defining everything the configuration has to offer, now and in the future. It also avoids having to add new params one by one as users request the ability to configure individual values.
Closes: #120
=> Allow adding arbitrary buildkit config

README.md, registry.go, task_test.go
Enable the oci-build task to load OCI images from a given path. The
original tarball loading still works, but now the task will detect if
the given path is a directory or a file.
If it's a directory then it tries loading the files at the path as an
OCI image and adds it to the image registry server that we spin up.
This will allow users to load multi-arch images from the
registry-image resource.
=> load OCI images with IMAGE_ARG_*

Dockerfile
Found out the the buildkitd package from Wolfi doesn't include the qemu binaries needed for multi-arch building. I tried to see if they had them in another package but my search turned up nothing.
Instead of using wolfi's package repo to install buildkit and the qemu binaries, we fall back to downloading the binaries from the official github release.
I built and tested the new image in a pipeline. With 0.13.0 the pipeline failed with the `exec format` error. With the updated image, I was able to successfully build the multi-arch image again.
=> Add qemu binaries back into the image

Dockerfile
To support user workarounds (https://github.com/concourse/oci-build-task/issues/70#issuecomment-933674965) for adding CA certs before starting the build process. Long-term, someone should add a way to add ca-certs.
Another potential workaround is to pass in additional buildkit config and set the CA certificate yourself: https://docs.docker.com/build/buildkit/configure/#setting-registry-certificates
Which can be done with `BUILDKIT_EXTRA_CONFIG` and the ability to mount task inputs at absolute locations now.
=> add ca-certificates to oci image
